CMD ["tsc *.ts --resolveJsonModule"]
WORKDIR "/Core"
CMD ["tsc *.ts --resolveJsonModule"]
WORKDIR "/RegisterHtml"
CMD ["tsc *.ts --resolveJsonModule"]
WORKDIR "/usr"
CMD ["tsc *.ts --resolveJsonModule"]